name: CMake Build (macOS x86-64)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      working-directory: ${{runner.workspace}}
      run: |
        rm -rf /usr/local/bin/2to3 # Temporary workaround suggested here - https://github.com/actions/virtual-environments/issues/2322#issuecomment-749211076
        brew update
        brew install sdl2 qt@5 libslirp libarchive libepoxy
    - name: Create build environment
      run: mkdir ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j$(sysctl -n hw.ncpu)
        mkdir dist
        cp -r melonDS.app dist
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS.app
        path: ${{runner.workspace}}/build/dist
